config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, controllers: {
        :omniauth_callbacks => "users/omniauth_callbacks"
      }

  devise_scope :user do
      get 'sign_out', :to => 'devise/sessions#destroy'
  end

  resources :tablets
end

app/models/tablet.rb
class Tablet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:clover]

  has_many :tablets

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.access_token = auth.credentials.token
      user.merchant_id = auth.extra.merchant_id
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/home_controller.rb
require 'clover'

class HomeController < ApplicationController


  def index
    @clover = Clover.new("#{current_user.access_token}", "#{current_user.merchant_id}")
    @item_names = []
    @clover.items['elements'].each do |item|
      @item_names.push(item['name'])
    end
    # @response = HTTParty.get("https://api.clover.com/v3/merchants/#{current_user.merchant_id}/items?access_token=#{current_user.access_token}")
  end

  def orders
    @clover = Clover.new("#{current_user.access_token}", "#{current_user.merchant_id}")

    @order_title = params["order_title"]
    @new_orders = @clover.new_order(@order_title)
  end

  private
  # for before_action filter later
  def set_clover
    @clover = Clover.new("#{current_user.access_token}", "#{current_user.merchant_id}")
  end
end

app/controllers/tablets_controller.rb
class TabletsController < ApplicationController
  before_action :set_tablet, only: [:show, :edit, :update, :destroy]
  before_action :set_clover, only: [:show, :new, :create, :edit, :update]

  # GET /tablets
  def index
    @tablets = Tablet.where(merchant_id: current_user.merchant_id)
  end

  # GET /tablets/1
  def show
    @current_orders = @clover.orders['elements']
  end

  # GET /tablets/new
  def new
    @tablet = Tablet.new
  end

  # GET /tablets/1/edit
  def edit
  end

  # POST /tablets
  def create
    @tablet = current_user.tablets.new(tablet_params)
    @tablet.merchant_id = current_user.merchant_id

    if @tablet.save
      redirect_to @tablet, notice: 'Tablet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tablets/1
  def update
    if @tablet.update(tablet_params)
      redirect_to @tablet, notice: 'Tablet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tablets/1
  def destroy
    @tablet.destroy
    redirect_to tablets_url, notice: 'Tablet was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tablet
      @tablet = Tablet.find(params[:id])
    end

    def set_clover
      @clover = Clover.new("#{current_user.access_token}", "#{current_user.merchant_id}")
    end

    # Only allow a trusted parameter "white list" through.
    def tablet_params
      params.require(:tablet).permit(:name, :merchant_id, :user_id, items: [])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  skip_before_filter :authenticate_user!

  def clover
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bv-navbar" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BaristaVision", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bv-navbar">
      <ul class="nav navbar-nav">
        <li class="<%= ('active' if controller_name == "tablets") %>">
          <%= link_to "Tablets", tablets_path %>
        </li>
        <li class="<%= ('active' if controller_name == "orders") %>">
          <%= link_to "Orders", root_path %>
        </li>
      </ul>
      <div class="navbar-right">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <div class="navbar-text">
              <em>
                <%= current_user.email %>
              </em>
            </div>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'navbar-link' do %>
                <i class="fa fa-sign-out"></i>
                Sign out
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_session_path, class: 'navbar-link' do %>
                <i class="fa fa-sign-in"></i>
                Sign in
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome to BaristaVision</h1>
<p>Let's make some coffee...</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="header">
    <%= render "navbar" %>
  </header>
  <div class="container">
    <%= render "flashes" %>
    <%= yield %>
  </div>
  <%= render "javascript" %>
</body>
</html>

app/views/tablets/_form.html.erb
<%= simple_form_for(@tablet,html: {class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :items, :collection => @clover.items['elements'].map { |item| item['name'] }, :as => :check_boxes, :include_hidden => false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tablets/edit.html.erb
<h1>Editing Tablet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tablet %> |
<%= link_to 'Back', tablets_path %>

app/views/tablets/index.html.erb
<div class="page-header">
  <h1>
    All Tablets
    <div class="pull-right">
      <%= link_to new_tablet_path, class: "btn btn-lg btn-success" do %>
        <i class="fa fa-plus"></i>
        New Tablet
      <% end %>
    </div>
  </h1>
</div>
<div class="row">
  <div class="col-md-6">
    <ul class="list-group">
      <% @tablets.each do |tablet| %>
        <li class="list-group-item">
          <%= link_to tablet_path(tablet) do %>
            <div class="">
              <h3><%= tablet.name %></h3>
            </div>
          <% end %>
          <p>Created by: <%= tablet.user.email %></p>
          <p>Items</p>
          <ul>
            <% tablet.items.each do |item| %>
              <li><%= item %></li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>



<h3>ignore, for reference only:</h3>


<h1>Listing Tablets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Merchant</th>
      <th>Items</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tablets.each do |tablet| %>
      <tr>
        <td><%= tablet.name %></td>
        <td><%= tablet.merchant_id %></td>
        <td><%= tablet.items %></td>
        <td><%= tablet.user %></td>
        <td><%= link_to 'Show', tablet %></td>
        <td><%= link_to 'Edit', edit_tablet_path(tablet) %></td>
        <td><%= link_to 'Destroy', tablet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tablet', new_tablet_path %>

app/views/tablets/new.html.erb
<h1>New Tablet</h1>

<%= render 'form' %>

<%= link_to 'Back', tablets_path %>

app/views/tablets/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @tablet.name %>
</p>

<p>
  <strong>Merchant:</strong>
  <%= @tablet.merchant_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @tablet.user %>
</p>

<p>
  <strong>Orders:</strong>
  <% @current_orders.each do |order| %>
    <p><%= order %></p>
    <% end %>
</p>


<%= link_to 'Edit', edit_tablet_path(@tablet) %> |
<%= link_to 'Back', tablets_path %>